# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: 7.3.29$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.cs
      **\AssemblyInfo.vb
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    FileVersionNumber: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: Copia dei file compilati
  inputs:
    SourceFolder: 'src/ARXivarNEXT.Client/bin/$(buildConfiguration)'
    Contents: '*.dll'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/pack/lib/netstandard1.3'

- task: CopyFiles@2
  displayName: Copia della licenza
  inputs:
    SourceFolder: ''
    Contents: 'license.txt'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/pack/license'

- task: CopyFiles@2
  displayName: Copia della licenza
  inputs:
    SourceFolder: 'src/ARXivarNEXT.Client'
    Contents: '*.csproj'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'