/* 
 * WebAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: data
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = ARXivarNEXT.Client.Client.SwaggerDateConverter;

namespace ARXivarNEXT.Client.Model
{
    /// <summary>
    /// Last number to use for enumeration check
    /// </summary>
    [DataContract]
    public partial class EnumerationCheckLastNumberDTO :  IEquatable<EnumerationCheckLastNumberDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnumerationCheckLastNumberDTO" /> class.
        /// </summary>
        /// <param name="businessUnit">Business unit of the enumeration.</param>
        /// <param name="documentTypeId">Document type Id of the enumeration.</param>
        /// <param name="splitFields">Split field of the enumeration.</param>
        /// <param name="lastValue">Last number of the enumeration.</param>
        public EnumerationCheckLastNumberDTO(BusinessUnitDTO businessUnit = default(BusinessUnitDTO), int? documentTypeId = default(int?), List<EnumerationCheckSplitFieldDTO> splitFields = default(List<EnumerationCheckSplitFieldDTO>), long? lastValue = default(long?))
        {
            this.BusinessUnit = businessUnit;
            this.DocumentTypeId = documentTypeId;
            this.SplitFields = splitFields;
            this.LastValue = lastValue;
        }
        
        /// <summary>
        /// Business unit of the enumeration
        /// </summary>
        /// <value>Business unit of the enumeration</value>
        [DataMember(Name="businessUnit", EmitDefaultValue=false)]
        public BusinessUnitDTO BusinessUnit { get; set; }

        /// <summary>
        /// Document type Id of the enumeration
        /// </summary>
        /// <value>Document type Id of the enumeration</value>
        [DataMember(Name="documentTypeId", EmitDefaultValue=false)]
        public int? DocumentTypeId { get; set; }

        /// <summary>
        /// Split field of the enumeration
        /// </summary>
        /// <value>Split field of the enumeration</value>
        [DataMember(Name="splitFields", EmitDefaultValue=false)]
        public List<EnumerationCheckSplitFieldDTO> SplitFields { get; set; }

        /// <summary>
        /// Last number of the enumeration
        /// </summary>
        /// <value>Last number of the enumeration</value>
        [DataMember(Name="lastValue", EmitDefaultValue=false)]
        public long? LastValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EnumerationCheckLastNumberDTO {\n");
            sb.Append("  BusinessUnit: ").Append(BusinessUnit).Append("\n");
            sb.Append("  DocumentTypeId: ").Append(DocumentTypeId).Append("\n");
            sb.Append("  SplitFields: ").Append(SplitFields).Append("\n");
            sb.Append("  LastValue: ").Append(LastValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EnumerationCheckLastNumberDTO);
        }

        /// <summary>
        /// Returns true if EnumerationCheckLastNumberDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EnumerationCheckLastNumberDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EnumerationCheckLastNumberDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BusinessUnit == input.BusinessUnit ||
                    (this.BusinessUnit != null &&
                    this.BusinessUnit.Equals(input.BusinessUnit))
                ) && 
                (
                    this.DocumentTypeId == input.DocumentTypeId ||
                    (this.DocumentTypeId != null &&
                    this.DocumentTypeId.Equals(input.DocumentTypeId))
                ) && 
                (
                    this.SplitFields == input.SplitFields ||
                    this.SplitFields != null &&
                    this.SplitFields.SequenceEqual(input.SplitFields)
                ) && 
                (
                    this.LastValue == input.LastValue ||
                    (this.LastValue != null &&
                    this.LastValue.Equals(input.LastValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BusinessUnit != null)
                    hashCode = hashCode * 59 + this.BusinessUnit.GetHashCode();
                if (this.DocumentTypeId != null)
                    hashCode = hashCode * 59 + this.DocumentTypeId.GetHashCode();
                if (this.SplitFields != null)
                    hashCode = hashCode * 59 + this.SplitFields.GetHashCode();
                if (this.LastValue != null)
                    hashCode = hashCode * 59 + this.LastValue.GetHashCode();
                return hashCode;
            }
        }
    }

}
