/* 
 * WebAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: data
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = ARXivarNEXT.Client.Client.SwaggerDateConverter;

namespace ARXivarNEXT.Client.Model
{
    /// <summary>
    /// Defines the information of the defaults preferences
    /// </summary>
    [DataContract]
    public partial class GraphometricSignaturePreferencesConfigurationDTO :  IEquatable<GraphometricSignaturePreferencesConfigurationDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GraphometricSignaturePreferencesConfigurationDTO" /> class.
        /// </summary>
        /// <param name="readerName">Gets or sets the reader name.</param>
        /// <param name="doNotAskForPin">Gets or sets whether asking for enter a PIN to the user.</param>
        /// <param name="pin">Gets or sets the defualt PIN value.</param>
        /// <param name="storeSignedDocumentInArxivar">Gets or sets whether to store the signed documents in ARXivar.</param>
        /// <param name="enableInformationLog">Gets or sets whether the information log should be enabled.</param>
        /// <param name="licenseFilePath">Gets or sets the license file (.fctsk) full path.</param>
        /// <param name="certificateFilePath">Gets or sets the certificate file (.pem) full path.</param>
        /// <param name="skipDocumentsSummaryUI">Gets or sets whether to skip the sign summary window.</param>
        public GraphometricSignaturePreferencesConfigurationDTO(string readerName = default(string), bool? doNotAskForPin = default(bool?), string pin = default(string), bool? storeSignedDocumentInArxivar = default(bool?), bool? enableInformationLog = default(bool?), string licenseFilePath = default(string), string certificateFilePath = default(string), bool? skipDocumentsSummaryUI = default(bool?))
        {
            this.ReaderName = readerName;
            this.DoNotAskForPin = doNotAskForPin;
            this.Pin = pin;
            this.StoreSignedDocumentInArxivar = storeSignedDocumentInArxivar;
            this.EnableInformationLog = enableInformationLog;
            this.LicenseFilePath = licenseFilePath;
            this.CertificateFilePath = certificateFilePath;
            this.SkipDocumentsSummaryUI = skipDocumentsSummaryUI;
        }
        
        /// <summary>
        /// Gets or sets the reader name
        /// </summary>
        /// <value>Gets or sets the reader name</value>
        [DataMember(Name="readerName", EmitDefaultValue=false)]
        public string ReaderName { get; set; }

        /// <summary>
        /// Gets or sets whether asking for enter a PIN to the user
        /// </summary>
        /// <value>Gets or sets whether asking for enter a PIN to the user</value>
        [DataMember(Name="doNotAskForPin", EmitDefaultValue=false)]
        public bool? DoNotAskForPin { get; set; }

        /// <summary>
        /// Gets or sets the defualt PIN value
        /// </summary>
        /// <value>Gets or sets the defualt PIN value</value>
        [DataMember(Name="pin", EmitDefaultValue=false)]
        public string Pin { get; set; }

        /// <summary>
        /// Gets or sets whether to store the signed documents in ARXivar
        /// </summary>
        /// <value>Gets or sets whether to store the signed documents in ARXivar</value>
        [DataMember(Name="storeSignedDocumentInArxivar", EmitDefaultValue=false)]
        public bool? StoreSignedDocumentInArxivar { get; set; }

        /// <summary>
        /// Gets or sets whether the information log should be enabled
        /// </summary>
        /// <value>Gets or sets whether the information log should be enabled</value>
        [DataMember(Name="enableInformationLog", EmitDefaultValue=false)]
        public bool? EnableInformationLog { get; set; }

        /// <summary>
        /// Gets or sets the license file (.fctsk) full path
        /// </summary>
        /// <value>Gets or sets the license file (.fctsk) full path</value>
        [DataMember(Name="licenseFilePath", EmitDefaultValue=false)]
        public string LicenseFilePath { get; set; }

        /// <summary>
        /// Gets or sets the certificate file (.pem) full path
        /// </summary>
        /// <value>Gets or sets the certificate file (.pem) full path</value>
        [DataMember(Name="certificateFilePath", EmitDefaultValue=false)]
        public string CertificateFilePath { get; set; }

        /// <summary>
        /// Gets or sets whether to skip the sign summary window
        /// </summary>
        /// <value>Gets or sets whether to skip the sign summary window</value>
        [DataMember(Name="skipDocumentsSummaryUI", EmitDefaultValue=false)]
        public bool? SkipDocumentsSummaryUI { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GraphometricSignaturePreferencesConfigurationDTO {\n");
            sb.Append("  ReaderName: ").Append(ReaderName).Append("\n");
            sb.Append("  DoNotAskForPin: ").Append(DoNotAskForPin).Append("\n");
            sb.Append("  Pin: ").Append(Pin).Append("\n");
            sb.Append("  StoreSignedDocumentInArxivar: ").Append(StoreSignedDocumentInArxivar).Append("\n");
            sb.Append("  EnableInformationLog: ").Append(EnableInformationLog).Append("\n");
            sb.Append("  LicenseFilePath: ").Append(LicenseFilePath).Append("\n");
            sb.Append("  CertificateFilePath: ").Append(CertificateFilePath).Append("\n");
            sb.Append("  SkipDocumentsSummaryUI: ").Append(SkipDocumentsSummaryUI).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GraphometricSignaturePreferencesConfigurationDTO);
        }

        /// <summary>
        /// Returns true if GraphometricSignaturePreferencesConfigurationDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of GraphometricSignaturePreferencesConfigurationDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GraphometricSignaturePreferencesConfigurationDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ReaderName == input.ReaderName ||
                    (this.ReaderName != null &&
                    this.ReaderName.Equals(input.ReaderName))
                ) && 
                (
                    this.DoNotAskForPin == input.DoNotAskForPin ||
                    (this.DoNotAskForPin != null &&
                    this.DoNotAskForPin.Equals(input.DoNotAskForPin))
                ) && 
                (
                    this.Pin == input.Pin ||
                    (this.Pin != null &&
                    this.Pin.Equals(input.Pin))
                ) && 
                (
                    this.StoreSignedDocumentInArxivar == input.StoreSignedDocumentInArxivar ||
                    (this.StoreSignedDocumentInArxivar != null &&
                    this.StoreSignedDocumentInArxivar.Equals(input.StoreSignedDocumentInArxivar))
                ) && 
                (
                    this.EnableInformationLog == input.EnableInformationLog ||
                    (this.EnableInformationLog != null &&
                    this.EnableInformationLog.Equals(input.EnableInformationLog))
                ) && 
                (
                    this.LicenseFilePath == input.LicenseFilePath ||
                    (this.LicenseFilePath != null &&
                    this.LicenseFilePath.Equals(input.LicenseFilePath))
                ) && 
                (
                    this.CertificateFilePath == input.CertificateFilePath ||
                    (this.CertificateFilePath != null &&
                    this.CertificateFilePath.Equals(input.CertificateFilePath))
                ) && 
                (
                    this.SkipDocumentsSummaryUI == input.SkipDocumentsSummaryUI ||
                    (this.SkipDocumentsSummaryUI != null &&
                    this.SkipDocumentsSummaryUI.Equals(input.SkipDocumentsSummaryUI))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReaderName != null)
                    hashCode = hashCode * 59 + this.ReaderName.GetHashCode();
                if (this.DoNotAskForPin != null)
                    hashCode = hashCode * 59 + this.DoNotAskForPin.GetHashCode();
                if (this.Pin != null)
                    hashCode = hashCode * 59 + this.Pin.GetHashCode();
                if (this.StoreSignedDocumentInArxivar != null)
                    hashCode = hashCode * 59 + this.StoreSignedDocumentInArxivar.GetHashCode();
                if (this.EnableInformationLog != null)
                    hashCode = hashCode * 59 + this.EnableInformationLog.GetHashCode();
                if (this.LicenseFilePath != null)
                    hashCode = hashCode * 59 + this.LicenseFilePath.GetHashCode();
                if (this.CertificateFilePath != null)
                    hashCode = hashCode * 59 + this.CertificateFilePath.GetHashCode();
                if (this.SkipDocumentsSummaryUI != null)
                    hashCode = hashCode * 59 + this.SkipDocumentsSummaryUI.GetHashCode();
                return hashCode;
            }
        }
    }

}
