/* 
 * WebAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: data
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using ARXivarNEXT.Client.Client;
using ARXivarNEXT.Client.Model;

namespace ARXivarNEXT.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGraphometricSettingsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets the general settings for the graphometric signature
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GraphometricSignatureGeneralSettingsDTO</returns>
        GraphometricSignatureGeneralSettingsDTO GraphometricSettingsGetGeneralSettings ();

        /// <summary>
        /// Gets the general settings for the graphometric signature
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GraphometricSignatureGeneralSettingsDTO</returns>
        ApiResponse<GraphometricSignatureGeneralSettingsDTO> GraphometricSettingsGetGeneralSettingsWithHttpInfo ();
        /// <summary>
        /// Gets the graphometric signature&#39;s user preferences based on the authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GraphometricSignatureUserPreferencesDTO</returns>
        GraphometricSignatureUserPreferencesDTO GraphometricSettingsGetUserPreferences ();

        /// <summary>
        /// Gets the graphometric signature&#39;s user preferences based on the authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GraphometricSignatureUserPreferencesDTO</returns>
        ApiResponse<GraphometricSignatureUserPreferencesDTO> GraphometricSettingsGetUserPreferencesWithHttpInfo ();
        /// <summary>
        /// Saves the graphometric signature&#39;s user preference for the current authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">The user preferences to save</param>
        /// <returns></returns>
        void GraphometricSettingsSaveUserPreferences (GraphometricSignatureUserPreferencesDTO model);

        /// <summary>
        /// Saves the graphometric signature&#39;s user preference for the current authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">The user preferences to save</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GraphometricSettingsSaveUserPreferencesWithHttpInfo (GraphometricSignatureUserPreferencesDTO model);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets the general settings for the graphometric signature
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of GraphometricSignatureGeneralSettingsDTO</returns>
        System.Threading.Tasks.Task<GraphometricSignatureGeneralSettingsDTO> GraphometricSettingsGetGeneralSettingsAsync ();

        /// <summary>
        /// Gets the general settings for the graphometric signature
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (GraphometricSignatureGeneralSettingsDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<GraphometricSignatureGeneralSettingsDTO>> GraphometricSettingsGetGeneralSettingsAsyncWithHttpInfo ();
        /// <summary>
        /// Gets the graphometric signature&#39;s user preferences based on the authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of GraphometricSignatureUserPreferencesDTO</returns>
        System.Threading.Tasks.Task<GraphometricSignatureUserPreferencesDTO> GraphometricSettingsGetUserPreferencesAsync ();

        /// <summary>
        /// Gets the graphometric signature&#39;s user preferences based on the authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (GraphometricSignatureUserPreferencesDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<GraphometricSignatureUserPreferencesDTO>> GraphometricSettingsGetUserPreferencesAsyncWithHttpInfo ();
        /// <summary>
        /// Saves the graphometric signature&#39;s user preference for the current authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">The user preferences to save</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GraphometricSettingsSaveUserPreferencesAsync (GraphometricSignatureUserPreferencesDTO model);

        /// <summary>
        /// Saves the graphometric signature&#39;s user preference for the current authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">The user preferences to save</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GraphometricSettingsSaveUserPreferencesAsyncWithHttpInfo (GraphometricSignatureUserPreferencesDTO model);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GraphometricSettingsApi : IGraphometricSettingsApi
    {
        private ARXivarNEXT.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GraphometricSettingsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GraphometricSettingsApi(String basePath)
        {
            this.Configuration = new ARXivarNEXT.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ARXivarNEXT.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GraphometricSettingsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GraphometricSettingsApi(ARXivarNEXT.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ARXivarNEXT.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ARXivarNEXT.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ARXivarNEXT.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ARXivarNEXT.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets the general settings for the graphometric signature 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GraphometricSignatureGeneralSettingsDTO</returns>
        public GraphometricSignatureGeneralSettingsDTO GraphometricSettingsGetGeneralSettings ()
        {
             ApiResponse<GraphometricSignatureGeneralSettingsDTO> localVarResponse = GraphometricSettingsGetGeneralSettingsWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the general settings for the graphometric signature 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GraphometricSignatureGeneralSettingsDTO</returns>
        public ApiResponse< GraphometricSignatureGeneralSettingsDTO > GraphometricSettingsGetGeneralSettingsWithHttpInfo ()
        {

            var localVarPath = "./api/GraphometricSettings/General";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GraphometricSettingsGetGeneralSettings", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GraphometricSignatureGeneralSettingsDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (GraphometricSignatureGeneralSettingsDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GraphometricSignatureGeneralSettingsDTO)));
        }

        /// <summary>
        /// Gets the general settings for the graphometric signature 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of GraphometricSignatureGeneralSettingsDTO</returns>
        public async System.Threading.Tasks.Task<GraphometricSignatureGeneralSettingsDTO> GraphometricSettingsGetGeneralSettingsAsync ()
        {
             ApiResponse<GraphometricSignatureGeneralSettingsDTO> localVarResponse = await GraphometricSettingsGetGeneralSettingsAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the general settings for the graphometric signature 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (GraphometricSignatureGeneralSettingsDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GraphometricSignatureGeneralSettingsDTO>> GraphometricSettingsGetGeneralSettingsAsyncWithHttpInfo ()
        {

            var localVarPath = "./api/GraphometricSettings/General";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GraphometricSettingsGetGeneralSettings", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GraphometricSignatureGeneralSettingsDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (GraphometricSignatureGeneralSettingsDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GraphometricSignatureGeneralSettingsDTO)));
        }

        /// <summary>
        /// Gets the graphometric signature&#39;s user preferences based on the authenticated user 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GraphometricSignatureUserPreferencesDTO</returns>
        public GraphometricSignatureUserPreferencesDTO GraphometricSettingsGetUserPreferences ()
        {
             ApiResponse<GraphometricSignatureUserPreferencesDTO> localVarResponse = GraphometricSettingsGetUserPreferencesWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the graphometric signature&#39;s user preferences based on the authenticated user 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GraphometricSignatureUserPreferencesDTO</returns>
        public ApiResponse< GraphometricSignatureUserPreferencesDTO > GraphometricSettingsGetUserPreferencesWithHttpInfo ()
        {

            var localVarPath = "./api/GraphometricSettings/UserPreferences";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GraphometricSettingsGetUserPreferences", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GraphometricSignatureUserPreferencesDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (GraphometricSignatureUserPreferencesDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GraphometricSignatureUserPreferencesDTO)));
        }

        /// <summary>
        /// Gets the graphometric signature&#39;s user preferences based on the authenticated user 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of GraphometricSignatureUserPreferencesDTO</returns>
        public async System.Threading.Tasks.Task<GraphometricSignatureUserPreferencesDTO> GraphometricSettingsGetUserPreferencesAsync ()
        {
             ApiResponse<GraphometricSignatureUserPreferencesDTO> localVarResponse = await GraphometricSettingsGetUserPreferencesAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the graphometric signature&#39;s user preferences based on the authenticated user 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (GraphometricSignatureUserPreferencesDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GraphometricSignatureUserPreferencesDTO>> GraphometricSettingsGetUserPreferencesAsyncWithHttpInfo ()
        {

            var localVarPath = "./api/GraphometricSettings/UserPreferences";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GraphometricSettingsGetUserPreferences", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GraphometricSignatureUserPreferencesDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (GraphometricSignatureUserPreferencesDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GraphometricSignatureUserPreferencesDTO)));
        }

        /// <summary>
        /// Saves the graphometric signature&#39;s user preference for the current authenticated user 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">The user preferences to save</param>
        /// <returns></returns>
        public void GraphometricSettingsSaveUserPreferences (GraphometricSignatureUserPreferencesDTO model)
        {
             GraphometricSettingsSaveUserPreferencesWithHttpInfo(model);
        }

        /// <summary>
        /// Saves the graphometric signature&#39;s user preference for the current authenticated user 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">The user preferences to save</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> GraphometricSettingsSaveUserPreferencesWithHttpInfo (GraphometricSignatureUserPreferencesDTO model)
        {
            // verify the required parameter 'model' is set
            if (model == null)
                throw new ApiException(400, "Missing required parameter 'model' when calling GraphometricSettingsApi->GraphometricSettingsSaveUserPreferences");

            var localVarPath = "./api/GraphometricSettings/UserPreferences";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null && model.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(model); // http body (model) parameter
            }
            else
            {
                localVarPostBody = model; // byte array
            }

            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GraphometricSettingsSaveUserPreferences", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Saves the graphometric signature&#39;s user preference for the current authenticated user 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">The user preferences to save</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GraphometricSettingsSaveUserPreferencesAsync (GraphometricSignatureUserPreferencesDTO model)
        {
             await GraphometricSettingsSaveUserPreferencesAsyncWithHttpInfo(model);

        }

        /// <summary>
        /// Saves the graphometric signature&#39;s user preference for the current authenticated user 
        /// </summary>
        /// <exception cref="ARXivarNEXT.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">The user preferences to save</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> GraphometricSettingsSaveUserPreferencesAsyncWithHttpInfo (GraphometricSignatureUserPreferencesDTO model)
        {
            // verify the required parameter 'model' is set
            if (model == null)
                throw new ApiException(400, "Missing required parameter 'model' when calling GraphometricSettingsApi->GraphometricSettingsSaveUserPreferences");

            var localVarPath = "./api/GraphometricSettings/UserPreferences";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null && model.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(model); // http body (model) parameter
            }
            else
            {
                localVarPostBody = model; // byte array
            }

            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GraphometricSettingsSaveUserPreferences", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                null);
        }

    }
}
